Legofit: parseopf.c File Reference
parseopf.c File Reference
Parse a .opf file, containing site pattern frequencies.
#include "parseopf.h"
#include "branchtab.h"
#include "lblndx.h"
#include "misc.h"
#include "string.h"
#include "tokenizer.h"
#include <stdio.h>
Functions
BranchTab * parseOpf (const char *fname, const LblNdx *lblndx)
Parse a .opf file containing observed site pattern frequencies.
Detailed Description
Parse a .opf file, containing site pattern frequencies.
Author
Alan R. Rogers
Copyright
Copyright (c) 2020, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
parseOpf()
BranchTab * parseOpf (const char * fname, const LblNdx * lblndx)
Parse a .opf file containing observed site pattern frequencies.
Recognizes comments, which extend from '#' to end-of-line.
References BranchTab_add(), BranchTab_new(), efopen(), eprintf(), LblNdx_getTipId(), LblNdx_size(), Tokenizer_free(), Tokenizer_new(), Tokenizer_print(), Tokenizer_split(), Tokenizer_strip(), and Tokenizer_token().