Legofit: resid.c File Reference
resid.c File Reference
#include "error.h"
#include "strdblqueue.h"
#include "misc.h"
#include "branchtab.h"
#include <strings.h>
#include <time.h>
Data Structures
struct Mapping
struct LblNdxBranchTab
Functions
void usage (void)
int Mapping_size (Mapping *self)
Mapping * Mapping_new (const char *lhs, const char *rhs)
void Mapping_free (Mapping *self)
const char * Mapping_lhs (Mapping *self)
const char * Mapping_rhs (Mapping *self)
void Mapping_print (Mapping *self, FILE *fp)
BranchTab * makeBranchTab (StrDblQueue *queue, LblNdx *lndx)
Construct a BranchTab from a StrDblQueue.
LblNdxBranchTab removePops (LblNdx lndx, BranchTab *bt, const char *deleteStr)
LblNdxBranchTab collapsePops (LblNdx lndx, BranchTab *bt, const char *collapseStr, const char *lbl)
int main (int argc, char **argv)
Variables
const char * usageMsg
Function Documentation
makeBranchTab()
BranchTab * makeBranchTab (StrDblQueue * queue, LblNdx * lndx)
Construct a BranchTab from a StrDblQueue.
The LblNdx translates site patterns from string representation to integer representation. Function returns a newly-allocated BranchTab. If queue is NULL, function returns NULL.
References BranchTab_add(), BranchTab_new(), LblNdx_getTipId(), LblNdx_print(), and LblNdx_size().
Variable Documentation
usageMsg
const char* usageMsg
Initial value:
=
    "\nusage: resid [options] <d1>  <d2> ... [-L <f1> <f2> ...]"
    " [-D x:y:z] \\\n"
    "   [-M c=a:b d=c:e:f ...]\n\n"
    "where <d1>, <d2>, ... are names of files containing observed\n"
    "site pattern frequencies, and <f1>, <f2>, ... contain the\n"
    "corresponding fitted values as produced by legofit. Must include\n"
    "at least one data file. Fitted files are optional. If present, their\n"
    "number must equal that of the data files. The optional -D argument\n"
    "introduces a colon-separated list of populations to delete. The\n"
    "optional -M argument introduces one or more remappings, which collapse\n"
    "two or more populations into a single label. Data files must precede\n"
    "the -L, -D, and -M arguments on the command line.\n\n"
    "Options:\n" "   -h or --help   : print this message.\n"