lego: boot.c File Reference
boot.c File Reference
Functions for a moving blocks bootstrap.
#include "boot.h"
#include "misc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <gsl/gsl_rng.h>
Data Structures
struct BootChr
Contains the all data involved in a moving blocks bootstrap of a single chromosome.
struct Boot
An array of BootChr pointers.
struct BootConf
Contains the data for a bootstrap confidence interval.
Functions
long LInt_div_round (long num, long denom)
Divide num by denom and round the result to the nearest integer.
static void BootChr_allocArrays (BootChr *self)
Allocate BootChr's arrays.
long adjustBlockLength (long lengthWanted, int nsnp)
Return a blocksize that is as close as possible to lengthWanted while still making length*nblock close to nsnp.
BootChr * BootChr_new (long nsnp, long nrep, int npat, long blocksize, gsl_rng *rng)
Constructor for class BootChr.
void BootChr_sanityCheck (const BootChr *self, const char *file, int line)
long BootChr_multiplicity (const BootChr *self, long snpndx, long rep)
How many copies of snp with index snpndx are present in a given repetition (rep)?
void BootChr_add (BootChr *self, long snpndx, int pat, double z)
Add one site pattern contribution to a BootChr structure.
long BootChr_nrep (const BootChr *self)
Return number of bootstrap repetitions.
long BootChr_npat (const BootChr *self)
Return number of site patterns.
long BootChr_nblock (const BootChr *self)
Return number of blocks.
long BootChr_nsnp (const BootChr *self)
Return number of SNPs.
void BootChr_free (BootChr *self)
Destructor.
void BootChr_aggregate (BootChr *self, int rep, int npat, double count[npat])
Add to an array the site pattern counts from the bootstrap replicate of a single chromosome.
Boot * Boot_new (int nchr, long nsnp[nchr], long nrep, int npat, long blocksize, gsl_rng *rng)
Constructor for class Boot.
void Boot_free (Boot *self)
Destructor for class Boot.
void Boot_add (Boot *self, int chr, long snpndx, int pat, double z)
Add one site pattern contribution to a Boot structure.
void Boot_aggregate (Boot *self, int rep, int npat, double count[npat])
Add to an array the site pattern counts from the bootstrap replicate of an entire genome.
void Boot_sanityCheck (const Boot *self, const char *file, int line)
double interpolate (double p, double *v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
void confidenceBounds (double *lowBnd, double *highBnd, double confidence, long len, double v[len])
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
void BootChr_print (const BootChr *self, FILE *ofp)
Print a BootChr object.
unsigned BootChr_multiplicity_slow (BootChr *self, long snp, long rep)
For debugging BootChr_multiplicity.
Detailed Description
Functions for a moving blocks bootstrap.
Author
Alan R. Rogers
Copyright
Copyright (c) 2016, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
long adjustBlockLength (long lengthWanted, int nsnp)
Return a blocksize that is as close as possible to lengthWanted while still making length*nblock close to nsnp.
References LInt_div_round(), and BootChr::nblock.
Referenced by BootChr_new().
void Boot_add (Boot * self, int chr, long snpndx, int pat, double z)
Add one site pattern contribution to a Boot structure.
Parameters
[in,out] self The Boot structure to modify.
[in] chr The index of the chromosome to modify.
[in] snpndx The index of the current snp.
[in] pat The index of the current site pattern.
[in] z the contribution of the snp to the site pattern.
References BootChr_add().
Referenced by generatePatterns().
void Boot_aggregate (Boot * self, int rep, int npat, double count[npat])
Add to an array the site pattern counts from the bootstrap replicate of an entire genome.
Parameters
[in] self Points to a Boot object.
[in] the index of the bootstrap replicate
[in] npat the number of site patterns
[out] count An array of doubles. The function will add to count[i] the contribution of site pattern i in bootstrap replicate rep.
References BootChr_aggregate(), BootChr::count, and BootChr::npat.
Referenced by generatePatterns().
void BootChr_add (BootChr * self, long snpndx, int pat, double z)
Add one site pattern contribution to a BootChr structure.
Parameters
[in,out] self The BootChr structure to modify.
[in] snpndx The index of the current snp.
[in] pat The index of the current site pattern.
[in] z the contribution of the snp to the site pattern.
References BootChr_multiplicity(), BootChr::npat, and BootChr::nsnp.
Referenced by Boot_add().
void BootChr_aggregate (BootChr * self, int rep, int npat, double count[npat])
Add to an array the site pattern counts from the bootstrap replicate of a single chromosome.
Parameters
[in] self Points to a BootChr object.
[in] the index of the bootstrap replicate
[in] npat the number of site patterns
[out] count An array of doubles. The function will add to count[i] the contribution of site pattern i in bootstrap replicate rep.
References BootChr::count.
Referenced by Boot_aggregate().
void confidenceBounds (double * lowBnd, double * highBnd, double confidence, long len, double v[len])
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
To calculate the lower bound (*lowBnd), the function calculates the total probability mass in the tails (1 - confidence) and divides this into two equal parts to find p, the probability mass in each tail. It then estimates a value L such that a fraction p of the data values are less than or equal to L. To find this value, the function uses linear interpolation between the sorted list of data values.
The upper bound (*highBnd) is calculated in an analogous fashion.
Parameters
[out] lowBnd,highBnd Calculated results will be written into these memory locations.
[in] confidence Fraction of sampling distribution that lies inside the confidence bounds.
[in] len The number of values inf v.
[in] v The vector of values.
Side Effects:
Sorts the vector v.
References compareDoubles(), and interpolate().
Referenced by generatePatterns().
double interpolate (double p, double * v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
Return NaN if len==0.
Referenced by confidenceBounds().
long LInt_div_round (long num, long denom)
Divide num by denom and round the result to the nearest integer.
Returns
an structure of type ldiv_t.
Referenced by adjustBlockLength(), and BootChr_new().