lego: cost.c File Reference
cost.c File Reference
#include "dprintf.h"
#include "cost.h"
#include "simsched.h"
#include "gptree.h"
#include "branchtab.h"
#include "patprob.h"
#include "misc.h"
#include <math.h>
#include <gsl/gsl_rng.h>
Functions
double costFun (int dim, double x[dim], void *jdata, void *tdata)
Calculate cost.
void * CostPar_dup (const void *arg)
Duplicate an object of class CostPar.
void CostPar_free (void *arg)
CostPar destructor.
Function Documentation
double costFun (int dim, double x[dim], void * jdata, void * tdata)
Calculate cost.
Parameters
[in] dim dimension of x
[in] x vector of parameter values.
jdata void pointer to a CostPar object, which contains exogeneous parameters of the cost function.
tdata void pointer to a random number generator
Returns
cost
References BranchTab_chiSqCost(), BranchTab_divideBy(), BranchTab_free(), BranchTab_KLdiverg(), BranchTab_normalize(), GPTree_feasible(), GPTree_setParams(), patprob(), and SimSched_getSimReps().
Referenced by initStateVec().