lego: exopar.c File Reference
exopar.c File Reference
Exogeneous parameters sampled from truncated normal distribution.
#include "exopar.h"
#include "misc.h"
#include "dtnorm.h"
#include <string.h>
#include <assert.h>
#include <gsl/gsl_randist.h>
Data Structures
struct ExoParItem
ExoParItem represents a parameter whose value will be repeatedly changed by sampling from a truncated Gaussian distribution.
struct ExoParList
A linked list of ExoParItem objects.
struct ExoPar
A container of ExoParItem objects.
Functions
static void ExoParItem_init (ExoParItem *self, double *ptr, double mean, double sd)
Initialize an ExoParItem object.
static void ExoParItem_sample (const ExoParItem *self, double low, double high, gsl_rng *rng)
Set *ptr by sampling from a truncated Gaussian distribution.
static int ExoParList_size (ExoParList *self)
Count links in list.
static ExoParList * ExoParList_add (ExoParList *old, double *ptr, double m, double sd)
Add a new link to list.
static void ExoParList_free (ExoParList *self)
Free linked list.
static int compare_ExoParItem_ExoParItem (const void *void_x, const void *void_y)
Compare two objects of type ExoParItem.
static int compare_dblPtr_ExoParItem (const void *void_x, const void *void_y)
Compare a double pointer to the "ptr" variable within an ExoParItem.
ExoPar * ExoPar_new (void)
Create an empty ExoPar container.
void ExoPar_freeze (ExoPar *self)
Freeze an ExoPar.
int ExoPar_sample (ExoPar *self, double *ptr, double low, double high, gsl_rng *rng)
If ptr is in ExoPar, then reset the value it points to with a random value generated by sampling from the truncated normal distribution.
void ExoPar_free (ExoPar *self)
ExoPar destructor.
void ExoPar_add (ExoPar *self, double *ptr, double m, double sd)
Add an exogeneous parameter to the table.
ExoPar * ExoPar_dup (const ExoPar *old)
Duplicate an ExoPar object.
void ExoPar_shiftPtrs (ExoPar *self, size_t offset, int sign)
Shift all pointers within an ExoPar.
Detailed Description
Exogeneous parameters sampled from truncated normal distribution.
Author
Alan R. Rogers
Copyright
Copyright (c) 2016, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
static int compare_dblPtr_ExoParItem (const void * void_x, const void * void_y) static
Compare a double pointer to the "ptr" variable within an ExoParItem.
Returns
-1, 0, or 1 to indicate that the double ptr is "<", "==", or ">" the pointer within the ExoParItem.
References ExoParItem::ptr.
Referenced by ExoPar_sample().
static int compare_ExoParItem_ExoParItem (const void * void_x, const void * void_y) static
Compare two objects of type ExoParItem.
Returns
-1, 0, or 1, to indicate that *x < *y, *x == *y, or *x > *y.
References ExoParItem::ptr.
Referenced by ExoPar_freeze().
void ExoPar_add (ExoPar * self, double * ptr, double m, double sd)
Add an exogeneous parameter to the table.
ptr points to the memory occupied by the parameter; m is the mean, sd the standard deviation.
References ExoParList_add().
void ExoPar_freeze (ExoPar * self)
Freeze an ExoPar.
This converts the internal linked list into a an array, which is sorted according to the internal pointer values. After freezing, nothing can be added to the ExoPar.
References compare_ExoParItem_ExoParItem(), ExoParList_free(), and ExoParList_size().
ExoPar* ExoPar_new (void)
Create an empty ExoPar container.
Returns
pointer to newly-allocated ExoPar.
int ExoPar_sample (ExoPar * self, double * ptr, double low, double high, gsl_rng * rng)
If ptr is in ExoPar, then reset the value it points to with a random value generated by sampling from the truncated normal distribution.
Parameters
self pointer to ExoPar
ptr memory address of the variable we will to modify
low low end of truncation interval
high high end of truncation interval
rng GSL random number generator
Returns
0 on success or 1 if ptr is not in ExoPar.
References compare_dblPtr_ExoParItem(), and ExoParItem_sample().
void ExoPar_shiftPtrs (ExoPar * self, size_t offset, int sign)
Shift all pointers within an ExoPar.
Parameters
[in] offset magnitude of shift
[in] sign direction of shift
static void ExoParItem_init (ExoParItem * self, double * ptr, double mean, double sd) static
Initialize an ExoParItem object.
Parameters
[in,out] ptr pointer to memory that will be controlled by this ExoParItem.
[in] mean mean of underlying Gaussian distribution
[in] sd standard deviation of underlying Gaussian
Side Effects:
Sets *ptr equal to mean
References ExoParItem::mean, ExoParItem::ptr, and ExoParItem::sd.
Referenced by ExoParList_add().
static void ExoParItem_sample (const ExoParItem * self, double low, double high, gsl_rng * rng) static
Set *ptr by sampling from a truncated Gaussian distribution.
Parameters
[in,out] self ExoParItem object to be modified
[in] low low end of truncation interval
[in] high high end of truncation interval
[in,out] rng GSL random number generator
References dtnorm().
Referenced by ExoPar_sample().
static ExoParList * ExoParList_add (ExoParList * old, double * ptr, double m, double sd) static
Add a new link to list.
Parameters
[in,out] old pointer to head of linked list
[in] ptr points to the memory occupied by the parameter to be controlled
[in] m the mean,
[in] sd the standard deviation.
Returns
pointer to new head of list
References ExoParItem_init().
Referenced by ExoPar_add().