lego: hashtab.c File Reference
hashtab.c File Reference
Hash table mapping keys (character strings) to values (void pointers).
#include "hashtab.h"
#include "misc.h"
#include <assert.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
Data Structures
struct El
A single key-value pair, with a pointer to the next one.
struct HashTab
The hash table.
struct HashTabSeq
Treats the hash table as a continuous sequence.
Macros
#define KEYSIZE 20
#define HASHDIM 32u
HASHDIM: dimention of hash table must be a power of 2.
Functions
El * El_new (const char *key)
Construct a new element with given key and NULL value.
void El_free (El *e)
Destroy a linked list of El objects.
El * El_find (El *self, El **found, const char *key)
Return El corresponding to key.
void El_map (El *self, void(*f)(void *value, void *data), void *data)
Apply function f(value, data) to all values in list.
void HashTabSeq_nextBucket (HashTabSeq *self)
Find the next bucket, ignoring empty buckets.
void freeValue (void *p, void *unused)
For use by HashTab_map. Will free every non-NULL value in table.
void * El_get (El *self)
Return the value pointer of an El object.
void El_set (El *self, void *value)
Set the value pointer of an El object.
void El_printShallow (El *self)
Print an El but not the entire linked list.
void El_print (El *self)
Print a linked list of El objects.
HashTab * HashTab_new (void)
HashTab constructor.
void HashTab_free (HashTab *self)
HashTab destructor.
El * HashTab_get (HashTab *self, const char *key)
Get the El object associated with key.
unsigned long HashTab_size (HashTab *self)
Return the number of elements in the HashTab.
void HashTab_print (HashTab *self)
Print a HashTab.
void HashTab_map (HashTab *self, void(*f)(void *value, void *data), void *data)
Apply function f(value, data) to all values in table.
HashTabSeq * HashTabSeq_new (HashTab *ht)
HashTabSeq constructor.
El * HashTabSeq_next (HashTabSeq *self)
Return the next element in table.
void HashTabSeq_free (HashTabSeq *self)
HashTabSeq destructor.
Detailed Description
Hash table mapping keys (character strings) to values (void pointers).
Author
Alan R. Rogers
Copyright
Copyright (c) 2016, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
El * El_find (El * self, El ** found, const char * key)
Return El corresponding to key.
If no such El exists, allocate a new one, insert it into hashtab, and return that. Note that El_find does not return NULL if key is missing.
References El_new().
Referenced by HashTab_get().
El* HashTab_get (HashTab * self, const char * key)
Get the El object associated with key.
If no such object exists in HashTab, insert a new one with NULL value pointer and return that.
References El_find(), and HASHDIM.
void HashTabSeq_nextBucket (HashTabSeq * self)
Find the next bucket, ignoring empty buckets.
If all remaining buckets are empty, set self->ndx equal to HASHDIM.
References HASHDIM.
Referenced by HashTabSeq_next().