lego: legofit.c File Reference
legofit.c File Reference
#include "branchtab.h"
#include "cost.h"
#include "diffev.h"
#include "gptree.h"
#include "lblndx.h"
#include "parstore.h"
#include "patprob.h"
#include "simsched.h"
#include <assert.h>
#include <float.h>
#include <getopt.h>
#include <gsl/gsl_sf_gamma.h>
#include <limits.h>
#include <pthread.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>
Functions
void usage (void)
void initStateVec (int ndx, void *void_p, int n, double x[n], gsl_rng *rng)
Initialize vector x.
void * ThreadState_new (void *notused)
void ThreadState_free (void *rng)
int main (int argc, char **argv)
Variables
pthread_mutex_t seedLock
unsigned long rngseed
volatile sig_atomic_t sigstat
Function Documentation
void initStateVec (int ndx, void * void_p, int n, double x[n], gsl_rng * rng)
Initialize vector x.
If ndx==0, simply copy the parameter vector from the GPTree object. Otherwise, randomize the GPTree first. This ensures that differential evolution starts with a set of points, one of which is the same as the values in the input file. This allows you to improve on existing estimates without starting from scratch each time.
References BranchTab_divideBy(), BranchTab_free(), BranchTab_hasSingletons(), BranchTab_normalize(), BranchTab_parse(), BranchTab_size(), BranchTab_toArrays(), costFun(), CostPar_dup(), CostPar_free(), diffev(), getNumCores(), GPTree_dup(), GPTree_free(), GPTree_getLblNdx(), GPTree_getParams(), GPTree_new(), GPTree_nFree(), GPTree_printParStore(), GPTree_printParStoreFree(), GPTree_randomize(), GPTree_setParams(), orderpat(), patLbl(), patprob(), sighandle(), SimSched_append(), SimSched_free(), SimSched_new(), SimSched_nStages(), SimSched_print(), and usage().