legofit: parstore.c File Reference
parstore.c File Reference
Manage a vector of parameters.
#include "parstore.h"
#include "strparmap.h"
#include "addrparmap.h"
#include "param.h"
#include "tinyexpr.h"
#include "misc.h"
#include "gptree.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <assert.h>
#include <float.h>
#include <gsl/gsl_rng.h>
Data Structures
struct ParStore
Macros
#define SET_CONSTR(par)
Functions
int ParStore_nFree (ParStore *self)
Return the number of free parameters.
int ParStore_nFixed (ParStore *self)
Return the number of fixed parameters.
int ParStore_nConstrained (ParStore *self)
Return the number of constrained parameters.
void ParStore_setFreeParams (ParStore *self, int n, double x[n])
Set vector of free parameters.
void ParStore_getFreeParams (ParStore *self, int n, double x[n])
Get vector of free parameters.
void ParStore_print (ParStore *self, FILE *fp)
Print a ParStore.
void ParStore_printFree (ParStore *self, FILE *fp)
Print free parameter values.
void ParStore_printConstrained (ParStore *self, FILE *fp)
Print constrained parameter values.
ParStore * ParStore_new (void)
Constructor.
ParStore * ParStore_dup (const ParStore *old)
Duplicate a ParStore.
void ParStore_free (ParStore *self)
Destructor.
void ParStore_addFreePar (ParStore *self, double value, double lo, double hi, const char *name, unsigned type)
Add a free parameter to ParStore.
void ParStore_addFixedPar (ParStore *self, double value, const char *name, unsigned type)
Add fixed parameter to ParStore.
void ParStore_addConstrainedPar (ParStore *self, const char *str, const char *name, unsigned type)
Add constrained parameter to ParStore.
const char * ParStore_getNameFree (ParStore *self, int i)
Get name of i'th free parameter.
double * ParStore_findPtr (ParStore *self, unsigned *type, const char *name)
Return pointer associated with parameter name.
int ParStore_isConstrained (const ParStore *self, const double *ptr)
Return 1 if ptr is the address of a constrained parameter; 0 otherwise.
void ParStore_sanityCheck (ParStore *self, const char *file, int line)
int ParStore_equals (ParStore *lhs, ParStore *rhs)
Return 1 if two ParStore objects are equal; 0 otherwise.
void ParStore_constrain_ptr (ParStore *self, double *ptr)
If ptr points to a constrained parameter, then set its value.
int ParStore_constrain (ParStore *self)
First check to see that free parameters obey boundary constraints.
void ParStore_randomize (ParStore *self, GPTree *gpt, gsl_rng *rng)
Randomize all FREE parameters except TIME parameters.
void ParStore_chkDependencies (ParStore *self)
void Bounds_sanityCheck (Bounds *self, const char *file, int line)
Make sure Bounds object is sane.
int Bounds_equals (const Bounds *lhs, const Bounds *rhs)
Return 1 if two Bounds objects are equal; 0 otherwise.
Detailed Description
Manage a vector of parameters.
This class solves the following problem. One algorithm requires that parameters be distributed throughout a network of nodes. Another requires that they all be collected into a vector. To accomplish both goals, ParStore maintains a vector of parameter values, together with high and low bounds on those values. When a new parameter is added to the ParStore, a pointer to that value is returned, so that it can be stored in the distributed data structure.
Copyright
Copyright (c) 2016, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Macro Definition Documentation
SET_CONSTR
#define SET_CONSTR (par)
Value:
do {                                            \
        (par)->value = te_eval((par)->constr);                          \
        if(isnan((par)->value)) {                                       \
            fprintf(stderr,"%s:%d: constraint returned NaN\n",          \
                    __FILE__,__LINE__);                                 \
            fprintf(stderr,"formula: %s = %s\n",                        \
                    (par)->name, (par)->formula);                       \
            exit(EXIT_FAILURE);                                         \
        }                                                               \
    }while(0)
Function Documentation
ParStore_constrain()
int ParStore_constrain (ParStore * self)
First check to see that free parameters obey boundary constraints.
If not, then return 1. Otherwise, set values of all constrained parameters and return 0.
Referenced by GPTree_dup(), GPTree_feasible(), GPTree_printParStore(), and GPTree_simulate().
ParStore_isConstrained()
int ParStore_isConstrained (const ParStore * self, const double * ptr)
Return 1 if ptr is the address of a constrained parameter; 0 otherwise.