lego: popnodetab.c File Reference
popnodetab.c File Reference
Hash table associating names of PopNode objects with pointers to PopNode objects.
#include "popnodetab.h"
#include "misc.h"
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
Data Structures
struct El
A single key-value pair, with a pointer to the next one.
struct PopNodeTab
The hash table.
Macros
#define KEYSIZE 20
#define PNT_DIM 32u
PNT_DIM: dimention of hash table must be a power of 2.
Functions
El * El_new (const char *key, PopNode *node)
Construct a new element with given key and node pointer.
void El_free (El *e)
Destroy a linked list of El objects.
El * El_insert (El *self, const char *key, PopNode *node, int *status)
Insert a new key/node pair into the linked list.
PopNodeTab * PopNodeTab_new (void)
PopNodeTab constructor.
void PopNodeTab_free (PopNodeTab *self)
PopNodeTab destructor.
PopNode * PopNodeTab_get (PopNodeTab *self, const char *key)
Get the PopNode object associated with key.
int PopNodeTab_insert (PopNodeTab *self, const char *key, PopNode *node)
Insert a PopNode into the table.
unsigned long PopNodeTab_size (PopNodeTab *self)
Return the number of elements in the PopNodeTab.
void PopNodeTab_print (PopNodeTab *self)
Print a PopNodeTab.
PopNode * PopNodeTab_check_and_root (PopNodeTab *self, const char *file, int line)
Check the sanity of each node and make sure there is only one root.
Detailed Description
Hash table associating names of PopNode objects with pointers to PopNode objects.
Author
Alan R. Rogers
Copyright
Copyright (c) 2016, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
El * El_insert (El * self, const char * key, PopNode * node, int * status)
Insert a new key/node pair into the linked list.
Usage:
El *list=NULL; int status; list = El_insert(list, key, node, &status); if(status != 0) printf("Error: key is already in list\n");
Parameters
self current element of list
[in] key a character string, the name of the current PopNode
[in] node pointer to PopNode object
[out] status pointer to int, which will be set to 0 on success or 1 if node is already in list.
Returns
pointer to self or to a newly-allocated El.
References El_new().
Referenced by PopNodeTab_insert().
PopNode* PopNodeTab_check_and_root (PopNodeTab * self, const char * file, int line)
Check the sanity of each node and make sure there is only one root.
Returns
root of population tree
References El::next, El::node, PNT_DIM, PopNode_root(), and PopNode_sanityFromLeaf().
Referenced by mktree().
PopNode* PopNodeTab_get (PopNodeTab * self, const char * key)
Get the PopNode object associated with key.
If no such object exists, return NULL.
References El::key, El::next, El::node, PNT_DIM, and strhash().
Referenced by parseDerive(), and parseMix().
int PopNodeTab_insert (PopNodeTab * self, const char * key, PopNode * node)
Insert a PopNode into the table.
Returns
0 on success; 1 if PopNode is already in table.
References El_insert(), PNT_DIM, and strhash().
Referenced by parseSegment().