lego: popnode.c File Reference
popnode.c File Reference
A single segment of a population tree.
#include "popnode.h"
#include "gene.h"
#include "misc.h"
#include "parstore.h"
#include <string.h>
#include <float.h>
#include <stdbool.h>
#include <gsl/gsl_randist.h>
Data Structures
struct NodeStore
This structure allows you to allocate PopNode objects in an array and then dole them out one at a time via calls to NodeStore_alloc.
Functions
static void PopNode_sanityCheck (PopNode *self, const char *file, int lineno)
Check sanity of PopNode.
static void PopNode_randomize_r (PopNode *self, Bounds bnd, gsl_rng *rng)
Recurse through the tree perturbing free parameters.
static void PopNode_gaussian_r (PopNode *self, Bounds bnd, ParStore *ps, gsl_rng *rng)
Traverse the population tree to reset the value of each Gaussian parameter by sampling from the relevant distribution.
void PopNode_sanityFromLeaf (PopNode *self, const char *file, int line)
Check for errors in PopNode tree. Call this from each leaf node.
PopNode * PopNode_root (PopNode *self)
Find root of population tree, starting from given node.
void PopNode_clear (PopNode *self)
Remove all references to samples from tree of populations.
void PopNode_untouch (PopNode *self)
Set all "touched" values to "false".
int PopNode_isClear (const PopNode *self)
Return 1 if PopNode tree is empty of samples.
void PopNode_print (FILE *fp, PopNode *self, int indent)
Print a PopNode and (recursively) its descendants.
void PopNode_printShallow (PopNode *self, FILE *fp)
Print a PopNode but not its descendants.
int PopNode_nsamples (PopNode *self)
Return the number of samples in a PopNode.
PopNode * PopNode_new (double *twoN, bool twoNfree, double *start, bool startFree, NodeStore *ns)
PopNode constructor.
void PopNode_addChild (PopNode *parent, PopNode *child)
Connect parent and child.
void PopNode_addSample (PopNode *self, Gene *gene)
Add a sample to a PopNode.
void PopNode_mix (PopNode *child, double *mPtr, bool mixFree, PopNode *introgressor, PopNode *native)
Connect a child PopNode to two parents.
void PopNode_newGene (PopNode *self, unsigned ndx)
PopNode constructor.
Gene * PopNode_coalesce (PopNode *self, gsl_rng *rng)
Coalesce gene tree within population tree.
void PopNode_free (PopNode *self)
Free node but not descendants.
void PopNode_randomize (PopNode *self, Bounds bnd, gsl_rng *rng)
Randomly perturb all free parameters in tree while maintaining inequality constraints.
void PopNode_gaussian (PopNode *self, Bounds bnd, ParStore *ps, gsl_rng *rng)
Reset the value of each Gaussian parameter by sampling from the relevant distribution.
int PopNode_feasible (const PopNode *self, Bounds bnd)
Return 1 if parameters satisfy inequality constraints, or 0 otherwise.
void PopNode_shiftParamPtrs (PopNode *self, size_t dp, int sign)
Add dp to each parameter pointer, using ordinary (not pointer) arithmetic.
void PopNode_shiftPopNodePtrs (PopNode *self, size_t dp, int sign)
Add dp to each PopNode pointer, using ordinary (not pointer) arithmetic.
NodeStore * NodeStore_new (int len, PopNode *v)
Allocate a new NodeStore, which provides an interface for getting PopNode objects, one at a time, out of a previously-allocated array v.
void NodeStore_free (NodeStore *self)
Destructor for NodeStore.
PopNode * NodeStore_alloc (NodeStore *self)
Return a pointer to an unused PopNode object within NodeStore.
void SampNdx_init (SampNdx *self)
Set everything to zero.
void SampNdx_addSamples (SampNdx *self, unsigned nsamples, PopNode *pnode)
Add samples for a single population.
void SampNdx_populateTree (SampNdx *self)
Put samples into the gene tree.
unsigned SampNdx_size (SampNdx *self)
int SampNdx_equals (const SampNdx *lhs, const SampNdx *rhs)
This equality check doesn't do much, because the pointers in different SampNdx objects don't have to be (in fact shouldn't be) equal.
void SampNdx_sanityCheck (SampNdx *self, const char *file, int line)
Check sanity of a SampNdx.
int SampNdx_ptrsLegal (SampNdx *self, PopNode *start, PopNode *end)
Return 1 if all pointers in SampNdx are in [start,end); return 0 otherwise.
void SampNdx_shiftPtrs (SampNdx *self, size_t dpop, int sign)
Shift all pointers within SampNdx by an offset of magnitude dpop.
Detailed Description
A single segment of a population tree.
Author
Alan R. Rogers PopNode objects can be linked together into a network, which models bifurcation of populations and gene flow among them. Each PopNode knows its size and duration. It has pointers to parents and children. If it has two parents, there is also a mixing parameter, which determines what fraction of the node derives from each parent.
Function Documentation
PopNode* NodeStore_alloc (NodeStore * self)
Return a pointer to an unused PopNode object within NodeStore.
Abort if none are left.
References eprintf().
Referenced by PopNode_new(), and SampNdx_shiftPtrs().
NodeStore* NodeStore_new (int len, PopNode * v)
Allocate a new NodeStore, which provides an interface for getting PopNode objects, one at a time, out of a previously-allocated array v.
Parameters
[in] len number of PopNode objects in array.
[in] v array of PopNode objects
Returns
newly-allocated NodeStore.
Referenced by countSegments(), GPTree_new(), and SampNdx_shiftPtrs().
void PopNode_gaussian (PopNode * self, Bounds bnd, ParStore * ps, gsl_rng * rng)
Reset the value of each Gaussian parameter by sampling from the relevant distribution.
References PopNode_gaussian_r(), and PopNode_untouch().
Referenced by GPTree_simulate().
static void PopNode_gaussian_r (PopNode * self, Bounds bnd, ParStore * ps, gsl_rng * rng) static
Traverse the population tree to reset the value of each Gaussian parameter by sampling from the relevant distribution.
Call PopNode_untouch before calling this function.
References ParStore_sample().
Referenced by PopNode_gaussian().
void PopNode_mix (PopNode * child, double * mPtr, bool mixFree, PopNode * introgressor, PopNode * native)
Connect a child PopNode to two parents.
Parameters
[in,out] child pointer to the child PopNode
[in] mPtr pointer to the gene flow variable
[in] mixFree 1 if mPtr is a free parameter; 0 otherwise
[in,out] introgressor pointer to the introgressing parent
[in,out] native pointer to the native parent
References eprintf(), and PopNode_sanityCheck().
Referenced by parseMix().
void PopNode_randomize (PopNode * self, Bounds bnd, gsl_rng * rng)
Randomly perturb all free parameters in tree while maintaining inequality constraints.
References PopNode_randomize_r(), and PopNode_untouch().
Referenced by GPTree_randomize(), and SampNdx_shiftPtrs().
static void PopNode_randomize_r (PopNode * self, Bounds bnd, gsl_rng * rng) static
Recurse through the tree perturbing free parameters.
Must call PopNode_untouch before calling this function.
References reflect().
Referenced by PopNode_randomize().
void PopNode_shiftParamPtrs (PopNode * self, size_t dp, int sign)
Add dp to each parameter pointer, using ordinary (not pointer) arithmetic.
Referenced by GPTree_dup(), and SampNdx_shiftPtrs().
void PopNode_shiftPopNodePtrs (PopNode * self, size_t dp, int sign)
Add dp to each PopNode pointer, using ordinary (not pointer) arithmetic.
Referenced by GPTree_dup(), and SampNdx_shiftPtrs().
void PopNode_untouch (PopNode * self)
Set all "touched" values to "false".
This algorithm is inefficient because it may process a single node multiple times. This happens when their is gene flow into the node, because then there multiple paths from the root to the node. It would be better to implement this as a shallow function (not recursive) and traverse the hash tab to execute it on each node exactly once.
Referenced by PopNode_gaussian(), and PopNode_randomize().
void SampNdx_addSamples (SampNdx * self, unsigned nsamples, PopNode * pnode)
Add samples for a single population.
Should be called once for each sampled population.
References eprintf().
Referenced by parseSegment(), and SampNdx_shiftPtrs().
int SampNdx_equals (const SampNdx * lhs, const SampNdx * rhs)
This equality check doesn't do much, because the pointers in different SampNdx objects don't have to be (in fact shouldn't be) equal.
Referenced by GPTree_equals(), and SampNdx_shiftPtrs().
void SampNdx_populateTree (SampNdx * self)
Put samples into the gene tree.
Should be done at the start of each simulation.
References PopNode_newGene().
Referenced by GPTree_simulate(), and SampNdx_shiftPtrs().
int SampNdx_ptrsLegal (SampNdx * self, PopNode * start, PopNode * end)
Return 1 if all pointers in SampNdx are in [start,end); return 0 otherwise.
Referenced by GPTree_dup(), and SampNdx_shiftPtrs().
void SampNdx_shiftPtrs (SampNdx * self, size_t dpop, int sign)
Shift all pointers within SampNdx by an offset of magnitude dpop.
If sign > 0, the shift is positive; otherwise it is negative.
References Gene_new(), NodeStore_alloc(), NodeStore_free(), NodeStore_new(), PopNode_addChild(), PopNode_addSample(), PopNode_new(), PopNode_nsamples(), PopNode_printShallow(), PopNode_randomize(), PopNode_shiftParamPtrs(), PopNode_shiftPopNodePtrs(), SampNdx_addSamples(), SampNdx_equals(), SampNdx_init(), SampNdx_populateTree(), SampNdx_ptrsLegal(), SampNdx_sanityCheck(), and unitTstResult().
Referenced by GPTree_dup().