lego: tabpat.c File Reference
tabpat.c File Reference
#include "binary.h"
#include "boot.h"
#include "dafreader.h"
#include "misc.h"
#include "strint.h"
#include "typedefs.h"
#include <ctype.h>
#include <errno.h>
#include <getopt.h>
#include <gsl/gsl_rng.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Data Structures
struct Stack
Treat a vector of tipId_t values as a push-down stack.
Macros
#define MAXCHR 24
Functions
static void usage (void)
Print usage message and die.
static Stack * Stack_new (int dim, tipId_t buff[dim])
This stack is local to this file.
static void Stack_free (Stack *stk)
Frees the stack but not the underlying buffer.
static void Stack_push (Stack *self, tipId_t x)
Add an entry to the stack, checking bounds.
static void generatePatterns (int bit, int npops, Stack *stk, tipId_t pat, int doSing)
Call as generatePatterns(0, npops, stk, 0); Recursive function, which generates all legal site patterns and pushes them onto a stack.
int main (int argc, char **argv)
Variables
const char * useMsg
Function Documentation
static void generatePatterns (int bit, int npops, Stack * stk, tipId_t pat, int doSing) static
Call as generatePatterns(0, npops, stk, 0); Recursive function, which generates all legal site patterns and pushes them onto a stack.
References Boot_add(), Boot_aggregate(), Boot_free(), Boot_new(), compare_tipId(), confidenceBounds(), DAFReader_allelesMatch(), DAFReader_chr(), DAFReader_clearChromosomes(), DAFReader_daf(), DAFReader_free(), DAFReader_multiNext(), DAFReader_new(), DAFReader_print(), DAFReader_printHdr(), DAFReader_rewind(), LblNdx_addSamples(), LblNdx_init(), patLbl(), Stack_free(), Stack_new(), Stack_push(), StrInt_free(), StrInt_get(), StrInt_insert(), StrInt_new(), and usage().
static Stack * Stack_new (int dim, tipId_t buff[dim]) static
This stack is local to this file.
It provides a bounds-controlled interface to an external array, which is passed as an argument, buff, to Stack_new.
Referenced by generatePatterns().
Variable Documentation
const char* useMsg
Initial value:
=
    "\nUsage: tabpat [options] <x>=<in1> <y>=<in2> ...\n"
    "   where <x> and <y> are arbitrary labels, and <in1> and <in2> are input\n"
    "   files in daf format. Writes to standard output."
    " Labels may not include\n"
    "   the character \":\"."