/**
@file bma.c
@page bma
@author Alan R. Rogers and Daniel Tabin
@brief Bootstrap model averaging

# `bma`: bootstrap model averaging

Bootstrap model averaging was proposed by Buckland et al (Biometrics,
53(2):603-618). It can be used with weights provided by any method of
model selection, including @ref bepe "bepe" and @ref clic
"clic". Model selection is applied to the real data and also to a set
of bootstrap replicates. The weight, \f$w_i\f$ of the i'th model is
the fraction of these data sets for which the i'th model wins.

The model-averaged estimator of a parameter, \f$\theta\f$, is the
average across models, weighted by \f$w_i\f$, of the model-specific
estimates of \f$\theta\f$. Models in which \f$\theta\f$ does not
appear are omitted from the weighted average.

To construct confidence intervals, we average across models within
each bootstrap replicate to obtain a bootstrap distribution of
model-averaged estimates.

Usage: bma <m1.msc> ... <mK.msc> -F <m1.flat> ... <mK.flat>

Here, the "mX" arguments refer to model "X". The "msc" suffix stands
for "model selection criterion". There are currently two options: @ref
bepe "bepe" and @ref clic "clic". Thus, the first command-line
argument might look like either "m1.bepe" or "m1.clic".

In either case, the "msc" files consist (apart from sharp-delimited
comments) of two columns. The first column gives the model selection
criterion, and the second column names the data file to which that
criterion refers. The first row should refer to the real data and the
remaining rows to bootstrap replicates. Model selection criteria are
defined so that low numbers indicate preferred models. I
will refer to these numbers as "badness" values.

After the `-F` argument comes a list of files, each of which can be
generated by @ref flatfile "flatfile.py". There must be a `.flat` file
for each model, so the number of `.flat` files should equal the number
of `.bepe` files. The first row of a `.flat` file is a header and
consists of column labels. Each column refers to a different
parameter, and the column labels are the names of these
parameters. The various `.flat` files need not agree about the number
of parameters or about the order of the parameters they share. But
shared parameters must have the same name in each `.flat` file.

After the header, each row in a `.flat` file refers to a different
data set. The first row after the header refers to the real data. Each
succeeding row refers to a bootstrap replicate. The number of rows
(excluding comments and the header) should agree with the numbers of
rows in the `.bepe` files.

In both types of input files, comments begin with a sharp character
and are ignored.

When `bma` runs, the first step is to calculate model weights,
\f$w_{i}\f$, where \f$i\f$ runs across models. The value of
\f$w_{ij}\f$ is the fraction data sets (i.e. of rows in the `.bepe`
files) for which \f$i\f$ is the best model (i.e. the one with the
lowest badness value.

In the next step, `bma` averages across models to obtain a
model-averaged estimate of each parameter. This is done separately for
each data set: first for the real data and then for each bootstrap
replicate. Some parameters may be missing from some models. In this
case, the average runs only across models that include the parameter,
and the weights are re-normalized so that they sum to 1 within this
reduced set of models.

Finally, the program uses the bootstrap distribution of model-averaged
parameter estimates to construct a 95% confidence interval for each
parameter. 

The program produces two output files. The first of these is written
to standard output and has the same form as the output of \ref
bootci "bootci.py". The first column consists of parameter names and the
2nd of model-averaged parameter estimates. The 3rd and 4th columns are
the lower and upper bounds of the confidence intervals.

The program also writes a file in the format of `ref flatfile
"flatfile.py". There is a header listing parameter labels. After the
header, row *i* gives the model-averaged estimate of each parameter
for the *i*th bootstrap replicate.

@copyright Copyright (c) 2018, Alan R. Rogers
<rogers@anthro.utah.edu>. This file is released under the Internet
Systems Consortium License, which can be found in file "LICENSE".
*/

#include "strdblqueue.h"
#include "strdbl.h"
#include "tokenizer.h"

typedef struct ModSelCrit {
    int dim;
    double *c;  // c[i] is the criterion for the i'th data set
    char **fname; // fname[i] points to name of i'th data set
} ModSelCrit;

// Maybe instead of an array of hash tables, I should have a single
// StrInt hash table that associates parameter names with column
// indices. Then the parameter values could be in a matrix.
typedef struct ModPar {
    int nrows, ncols;
    StrDbl **par // par[i] is a hash table of estimates from the i'th
                 // data set.
    char **fname; // fname[i] points to name of i'th data set
} ModPar;

void usage(void);
ModSelCrit *ModSelCrit_new(const char *fname);
void ModSelCrit_free(ModSelCrit *self);
int ModSelCrit_compare(ModSelCrit *x, ModSelCrit *y);
int ModSelCrit_dim(ModSelCrit *self);
ModPar *ModPar_new(const char *fname);

const char *usageMsg =
    "Usage: bma <m1.msc> ... <mK.msc> -F <m1.flat> ... <mK.flat>\n"
    "\n"
    "Here, the \"mX\" arguments refer to model \"X\". The \"msc\" suffix\n"
    "stands for \"model selection criterion\". There are currently two\n"
    "options: \"bepe\" and \"clic\". Thus, the first command-line\n"
    "argument might look like either \"m1.bepe\" or \"m1.clic\".\n\n"
    "In either case, the \"msc\" files consist (apart from sharp-delimited\n"
    "comments) of two columns. The first column gives the model selection\n"
    "criterion, and the second column names the data file to which that\n"
    "criterion refers. The first row should refer to the real data and the\n"
    "remaining rows to bootstrap replicates. Model selection criteria are\n"
    "defined so that low numbers indicate preferred models.\n\n"
    "After the \"-F\" argument comes a list of files, each of which can be\n"
    "generated by \"flatfile.py\". There must be a \".flat\" file\n"
    "for each model, so the number of \".flat\" files should equal the\n"
    "number of \".bepe\" files. The first row of a \".flat\" file is a header\n"
    "and consists of column labels. Each column refers to a different\n"
    "parameter, and the column labels are the names of these parameters.\n"
    "The various \".flat\" files need not agree about the number of\n"
    "parameters or about the order of the parameters they share. But\n"
    "shared parameters must have the same name in each \".flat\" file.\n\n"
    "After the header, each row in a \".flat\" file refers to a different\n"
    "data set. The first row after the header refers to the real data. Each\n"
    "succeeding row refers to a bootstrap replicate. The number of rows\n"
    "(excluding comments and the header) should agree with the numbers of\n"
    "rows in the \".bepe\" files.\n\n"
    "In both types of input files, comments begin with a sharp character\n"
    "and are ignored.\n";

void usage(void) {
    fputs(usageMsg, stderr);
    exit(EXIT_FAILURE);
}

/// Construct a new object of type ModSelCrit by parsing a file.
/// Return NULL on failure.
ModSelCrit *ModSelCrit_new(const char *fname) {
    FILE *fp = fopen(fname, "r");
    if(fp == NULL) {
        fprintf(stderr,"%s:%d: can't read file \"%s\"\n",
                __FILE__,__LINE__,fname);
        exit(EXIT_FAILURE);
    }
    char buff[200];

    // 1st pass counts lines
    int dim=0;
    while(1) {
        if(fgets(buff, sizeof buff, fp) == NULL) {
            break;
        }
        if(strchr(buff, '\n') == NULL && !feof(stdin)) {
            fprintf(stderr, "%s:%d: Buffer overflow. size=%zu\n",
                    __FILE__, __LINE__, sizeof(buff));
            exit(EXIT_FAILURE);
        }
        char *next = stripWhiteSpace(buff);
        assert(next);
        if(*next == '#' || strlen(next)==0)
            continue;
        ++dim;
    }

    ModSelCrit *msc = malloc(sizeof(ModSelCrit));
    if(msc==NULL) {
        fprintf(stderr,"%s:%d: bad malloc\n",__FILE__,__LINE__);
        exit(EXIT_FAILURE);
    }

    msc->dim = dim;
    msc->c = malloc(dim * sizeof(msc->c[0]));
    msc->fname = malloc(dim * sizeof(msc->fname[0]));
    if(msc->c==NULL || msc->fname==NULL) {
        fprintf(stderr,"%s:%d: bad malloc\n",__FILE__,__LINE__);
        exit(EXIT_FAILURE);
    }

    int line=0;
    while(1) {
        if(fgets(buff, sizeof buff, fp) == NULL)
            break;
        if(strchr(buff, '\n') == NULL && !feof(stdin)) {
            fprintf(stderr, "%s:%d: Buffer overflow. size=%zu\n",
                    __FILE__, __LINE__, sizeof(buff));
            exit(EXIT_FAILURE);
        }
        assert(line < msc->dim);
        char *next = stripWhiteSpace(buff);
        assert(next);
        if(*next == '#' || strlen(next)==0)
            continue;
        char *valstr = strsep(&next, " \t");
        next = stripWhiteSpace(next);
        if(valstr==NULL || next==NULL || strlen(next)==0) {
            fprintf(stderr,"%s:%d: can't parse file %s\n",
                    __FILE__,__LINE__, fname);
            exit(EXIT_FAILURE);
        }
        msc->c[line] = strtod(valstr, NULL);
        msc->fname[line] = strdup(next);
        if(msc->fname[line] == NULL) {
            fprintf(stderr,"%s:%d: bad strdup\n",__FILE__,__LINE__);
            exit(EXIT_FAILURE);
        }
        ++line;
    }
    return msc;
}

void ModSelCrit_free(ModSelCrit *self) {
    int i;
    for(i=0; i < self->dim; ++i) {
        if(self->fname[i])
            free(self->fname[i]);
    }
    free(self->fname);
    free(self->c);
    free(self);
}

// Compares dimensions and filenames. Return 0 if x and y agree.
int ModSelCrit_compare(ModSelCrit *x, ModSelCrit *y) {
    int i, diff;

    diff = x->dim - y->dim;
    if(diff)
        return diff;

    for(i=0; i < x->dim; ++i) {
        diff = strcmp(x->fname[i], y->fname[i]);
        if(diff)
            return diff;
    }
    return 0;
}

int ModSelCrit_dim(ModSelCrit *self) {
    return self->dim;
}

ModPar *ModPar_new(const char *fname) {
    FILE *fp = fopen(fname, "r");
    if(fp == NULL) {
        fprintf(stderr,"%s:%d: can't read file \"%s\"\n",
                __FILE__,__LINE__,fname);
        exit(EXIT_FAILURE);
    }
    char buff[4096];
    Tokenizer *tkz = Tokenizer_new(100); // room for 100 parameters

    // 1st pass counts rows and columns
    int nrows=0, ncols=0, ntokens;
    while(1) {
        if(fgets(buff, sizeof buff, fp) == NULL) {
            break;
        }
        if(strchr(buff, '\n') == NULL && !feof(stdin)) {
            fprintf(stderr, "%s:%d: Buffer overflow. size=%zu\n",
                    __FILE__, __LINE__, sizeof(buff));
            exit(EXIT_FAILURE);
        }
        ntokens = Tokenizer_split(tkz, buff, " \t");
        ntokens = Tokenizer_strip(tkz, " \n\t");
        if(ncols == 0) {
            ncols = ntokens;
        }else{
            if(ncols != ntokens) {
                fprintf(stderr,"%s:%d: inconsistent row lengths in file %s\n",
                        __FILE__,__LINE__,fname);
                exit(EXIT_FAILURE);
            }
            ++nrows;
        }
    }

    ModPar *self = malloc(sizeof(ModPar));
    if(self==NULL) {
        fprintf(stderr,"%s:%d: bad malloc\n",__FILE__,__LINE__);
        exit(EXIT_FAILURE);
    }

    self->nrows = nrows;
    char *parName[ncols];
    

    ModSelCrit *self = malloc(sizeof(ModSelCrit));
    if(self==NULL) {
        fprintf(stderr,"%s:%d: bad malloc\n",__FILE__,__LINE__);
        exit(EXIT_FAILURE);
    }

    self->nrows = nrows;
    self->c = malloc(nrows * sizeof(self->c[0]));
    self->fname = malloc(nrows * sizeof(self->fname[0]));
    if(self->c==NULL || self->fname==NULL) {
        fprintf(stderr,"%s:%d: bad malloc\n",__FILE__,__LINE__);
        exit(EXIT_FAILURE);
    }

    int line=0;
    while(1) {
        if(fgets(buff, sizeof buff, fp) == NULL)
            break;
        if(strchr(buff, '\n') == NULL && !feof(stdin)) {
            fprintf(stderr, "%s:%d: Buffer overflow. size=%zu\n",
                    __FILE__, __LINE__, sizeof(buff));
            exit(EXIT_FAILURE);
        }
        assert(line < self->nrows);
        char *next = stripWhiteSpace(buff);
        assert(next);
        if(*next == '#' || strlen(next)==0)
            continue;
        char *valstr = strsep(&next, " \t");
        next = stripWhiteSpace(next);
        if(valstr==NULL || next==NULL || strlen(next)==0) {
            fprintf(stderr,"%s:%d: can't parse file %s\n",
                    __FILE__,__LINE__, fname);
            exit(EXIT_FAILURE);
        }
        self->c[line] = strtod(valstr, NULL);
        self->fname[line] = strdup(next);
        if(self->fname[line] == NULL) {
            fprintf(stderr,"%s:%d: bad strdup\n",__FILE__,__LINE__);
            exit(EXIT_FAILURE);
        }
        ++line;
    }
    return self;
}

int main(int argc, char **argv) {
    time_t currtime = time(NULL);

    hdr("bma: bootstrap model average");
#if defined(__DATE__) && defined(__TIME__)
    printf("# Program was compiled: %s %s\n", __DATE__, __TIME__);
#endif
    printf("# Program was run: %s\n", ctime(&currtime));

    int i, j, nmodels = 0, nflat = 0, gotDashF = 0;

    // first pass through arguments: count files
    for(i = 1; i < argc; i++) {
        if(argv[i][0] == '-') {
            if(strcmp(argv[i], "-F") == 0) {
                gotDashF = 1;
                continue;
            } else
                usage();
        }
        if(gotDashF)
            ++nflat;
        else
            ++nmodels
    }
    if(nfiles != nflat) {
        fprintf(stderr, "%s:%d\n"
                " Inconsistent number of files!"
                " %d model selection criterion files and %d flat files\n",
                __FILE__, __LINE__, nmodels, nflat);
        usage();
    }

    if(nmodels < 2)
        usage();

    const char *mscnames[nmodels];
    const char *flatnames[nmodels];

    // first pass through arguments: put file names in arrays
    gotDashF=0;
    j=0;
    for(i = 1; i < argc; i++) {
        if(argv[i][0] == '-') {
            if(strcmp(argv[i], "-F") == 0) {
                gotDashF = 1;
                j=0;
                continue;
            } else
                usage();
        }
        if(gotDashF)
            flatnames[j++] = argv[i];
        else
            mscnames[j++] = argv[i];
    }

    ModSelCrit *msc[nmodels];

    // Parse msc files and check for consistency
    for(i=0; i< nmodels; ++i) {
        msc[i] = ModSelCrit_new(mscnames[i]);
        if(i>0) {
            if(ModSelCrit_compare(msc[0], msc[i])) {
                fprintf(stderr,"%s:%d: inconsistent files: %s and %s\n",
                        __FILE__,__LINE__,mscnames[i], mscnames[i]);
            }
        }
    }

    int nrows = ModSelCrit_dim(msc[0]);

    // Flat files have the same number of rows as msc files. They have
    // a column for each parameter, and the parameters may not agree
    // across files. This suggests that we need a matrix of hash
    // tables. Each row represents a data set, each column a model,
    // and the parameter values are in the hash tables.
    StrDbl *par[nrows][nmodels];
    for(i=0; i < nrows; ++i) {
        for(j=0; j<nmodels; ++j)
            par[i][j] = StrDbl_new();
    }
    
}
